### PR TITLE
Completed issue2

### PR DESCRIPTION
**Pull request by apurvabakshi**
Completed issue2 for Image Sharer App.
Functionalities added:
1. Image submission form added
2. Only valid images are accepted
3. Proper flash error messages are displayed for invalid images
4. Database, migrations are created. Links are persisted in the database

### CODE REVIEW

**Comment by justinpearsonappfolio** [comment]
[Issue 2: Save Image Link](https://trello.com/c/nWUHF7eq/8-issue-2-save-image-link)

**Comment by apurvabakshi** [comment]
[Issue 2: Save Image Link](https://trello.com/c/nWUHF7eq/8-issue-2-save-image-link)

**Comment by apurvabakshi** [comment]
[Issue 2: Save Image Link](https://trello.com/c/nWUHF7eq/8-issue-2-save-image-link)

**Comment by apurvabakshi** [comment]
[Issue 2: Save Image Link](https://trello.com/c/nWUHF7eq/8-issue-2-save-image-link)

**Pull request merged**
